### ISSUE TITLE
[Oppia Android] Oppiabot did not close a PR that was force pushed

### ISSUE THREAD

**Issue by BenHenning** [oppia/oppiabot#295] opened 2021-10-22 00:22 UTC
**Describe the bug**
See https://github.com/oppia/oppia-android/pull/3952. The author force-pushed their branch, but Oppiabot didn't detect & close it. Is there a specific feature that needs to be enabled for Oppia Android to make sure this works?

**To Reproduce**
Steps to reproduce the behavior: Unknown; I didn't try to repro it. Presumably any force push should demonstrate that Oppiabot isn't closing those PRs, but it's unclear if there's anything special about the PR above.

**Observed behavior**
The PR author force-pushed a branch & Oppiabot did not close the PR.

**Expected behavior**
I'm expecting that Oppiabot leaves a message & closes any PRs with force pushes. Is that not the case?

**Screenshots**
None -- see PR above.

**Additional context**
None

**Comment by seanlip** [comment] 2023-01-06 04:24
Duplicate of #298

**Closed by seanlip** 2023-01-06 04:24 UTC
