### ISSUE TITLE
Investigate issue with Oppiabot's comments

### ISSUE THREAD

**Issue by jameesjohn** [oppia/oppiabot#175] opened 2020-12-29 05:17 UTC
Oppiabot's comment when a new user gets added to the code owners file is unreadable and looks incorrect. This needs to be investigated and fixed appropriately.

For context, see https://github.com/oppia/oppia/pull/11478#issuecomment-749875175, https://github.com/oppia/oppia/pull/11478#issuecomment-749886142.

**Comment by b2pacific** [comment] 2021-02-15 11:30
I want to work on this issue. @jameesjohn can you assign this to me?

**Comment by jameesjohn** [comment] 2021-02-15 11:53
Hi @b2pacific, I think this issue might be a bit complex for a first-time contributor. You might want to look into https://github.com/oppia/oppiabot/issues/198.

**Comment by nlok5923** [comment] 2021-03-17 11:26
@jameesjohn sir it currently takes the latest updated code owners and then it appends all the  file whose codeowners has changed to the same comment.

Sir i am interested in this issue please can  you let me know what should be the actual behaviour

**Comment by Naman-1234** [comment] 2021-04-01 10:40
@jameesjohn  and @vojtechjelinek Sir I would like to work on this issue, Could you Please assign me this one. Thanks.

**Comment by seanlip** [comment] 2023-01-06 04:37
Duplicate of #236 .

**Closed by seanlip** 2023-01-06 04:37 UTC
Labels: Priority: Medium
