### ISSUE TITLE
New contributors facing problem after they open a PR.

### ISSUE THREAD

**Issue by prafulbbandre** [oppia/oppiabot#321] opened 2023-05-23 10:19 UTC
**Is your feature request related to a problem? Please describe.**
Currently the author has to assign the required reviewers to review the PR after all the tests are passed. Which is so difficult to understand for the new contributor's as the oppiabot doesn't suggest anything at all to the contributor's. So the Pr gets closed as the new contributor's dont know what to do.
 
In this PR https://github.com/oppia/oppia/pull/18126 the new contributor (nicolesosa) does not know what to do after his test are passed and oppia bot closed the PR.

**Describe the solution you'd like**
Once the Pr is open by a new contributor oppiabot must ask them if they need help.
    Like: Hi @author Thanks for the PR. If you need help regarding PR Please comment **@helper_username HELP** and someone from the helper team will get assigned to your PR.

And after that once all the Tests are passed it should suggest the Author to asssign the Reviewers for the Review.
   Like: Hi @author All your tests are passed, Please assign Reviewers so that they could Approve the PR or Request changes by commenting @reviewer_username PTAL

**Describe alternatives you've considered**
Or once the Pr is open by author the oppia bot should comment :

Thanks for the PR. If you need help regarding PR Please comment **@helper_username HELP** and someone from the helper team will get assigned to your PR.
After All your tests are passed, Please assign Reviewers so that they could Approve the PR or Request changes by commenting @reviewer_username PTAL

**Additional context**

**Comment by gp201** [comment] 2023-05-26 10:04
Closing this issue since it is similar to #320. If you want to discuss the issue please do so in #320

**Closed by gp201** 2023-05-26 10:04 UTC

**Comment by gp201** [comment] 2023-05-28 18:46
After identifying a bug as the root cause of the problem, our team made a decision to prioritize the resolution of the existing reviewer assignment functionality rather than introducing more messages that could potentially clutter up the contributor's PRs.
